### ISSUE TITLE
Communicate our mission statement clearly

### ISSUE THREAD

**Issue by DDCreationStudios** [DevelopersRising/DevelopersRising#24]
According to https://github.com/DevelopersRising/DevelopersRising/issues/4 

We should communicate on:
- [x] homepage
- [x] social media
- [x] offical docs

**Comment by robeerob** [comment]
@DDCreationStudios Would you agree that we now have it covered in our official docs, with a short slogan and more information on how we are accomplishing that slogan via our meetup work?

**Comment by DDCreationStudios** [comment]
@robeerob What do you mean? Can you elaborate? :) 

I just meant to put the mission statement on all platforms. For example in the meetup.com about section. Or the twitter about section. Or facebook , etc.

**Comment by robeerob** [comment]
@DDCreationStudios Yes, understood the overall issue topic. But I checked off the "official docs" part, and wanted you to verify that you also consider that part of the issue completed. Homepage and social media still remains, of course.

**Comment by DDCreationStudios** [comment]
@robeerob  Oh yes! Agreed :)

**Comment by robeerob** [comment]
@DDCreationStudios Status update: Will look into this over the next week and a half. A bit busy, and haven't been on top of this. Feel free to move to next sprint.

**Comment by DDCreationStudios** [comment]
Done ✅
