### ISSUE TITLE
Set social media guidelines

### ISSUE THREAD

**Issue by DDCreationStudios** [DevelopersRising/DevelopersRising#3]
- what # to use
- targeting
- etc

**Comment by robeerob** [comment]
I will work on this over the next few days.

**Comment by robeerob** [comment]
Do we have social media accounts already? If not, I can create an issue and take action on that as well.

**Comment by robeerob** [comment]
Awesome! Could you please add me as admin for the Facebook page and Meetup group? And Instagram if they have something similar, please.

**Comment by DDCreationStudios** [comment]
opened #10
