### ISSUE TITLE
Communicate vacant positions of the Verein

### ISSUE THREAD

**Issue by DDCreationStudios** [DevelopersRising/DevelopersRising#36]
Communicate the vacant positions on:
- [x] At October meetup event Metalab
- [x] social media
- [x] meetup.com
- [x] Github (DevR and FCCV)
- [x] Newsletter (not established)
- [X] Homepage

**Comment by robeerob** [comment]
@DDCreationStudios Status update: Will look into this over the next week and a half. A bit busy, and haven't been on top of this. Feel free to move to next sprint.

**Comment by DDCreationStudios** [comment]
added on DR homepage, see https://developersrising.herokuapp.com/

**Comment by DDCreationStudios** [comment]
@robeerob can you check out the posts of the positions on our social media channels? do you think it makes sense? 
after that we can close the issue and close the sprint :)

**Comment by robeerob** [comment]
Will look at it now 😉🙌

**Comment by robeerob** [comment]
[Done.](https://twitter.com/DevsRising/status/928721689596317696)

We can discuss if we want to spread it in different ways via social media as well, but I think this is a good start.
