### ISSUE TITLE
Improve readme with stats/benefits/achievements

### ISSUE THREAD

**Issue by robeerob** [DevelopersRising/DevelopersRising#38]
Inspired by the "About us" section on the [Vue.js Conference Amsterdam](https://www.vuejs.amsterdam/) website, I propose to add similar stats to our own readme. @DDCreationStudios What do you think?

Something like this...

<hr />

Our goal is to help, connect and inspire. Here are some of the things we've accomplished:

- 1000+ Meetup Members
- 20+ Successful Free Meetups
- 20+ Awesome Speakers
- 5+ Sponsors And Partners Involved 
- 4+ Active Open Source Repos
- Founded 3 Meetup Groups

**Comment by DDCreationStudios** [comment]
Great idea! @robeerob  🚀  We wil definitely have that in the about section 💪 I will create an issue in the homepage repo.
