### ISSUE TITLE
agree on a mission statement

### ISSUE THREAD

**Issue by DDCreationStudios** [DevelopersRising/DevelopersRising#4]

**Comment by DDCreationStudios** [comment]
@robeerob first idea: "We put aspiring developers in jobs, help existing developers grow and hobbyists thrive."

**Comment by DDCreationStudios** [comment]
We agree on providing 3 statements each.

Mine are:
-
1.  "DevelopersRising - Connecting Programmers, empowering beginners and help improving experienced ones"
2.  "Improving skills for all kinds of programmers"
3. "Empower beginners, connect experienced ones and fill gaps for masters"

@robeerob

**Comment by robeerob** [comment]
## Mine are:

1. "We connect aspiring developers with potential employers, help existing developers grow and hobbyists **thrive."**
2. "Inspire, empower and support learning and growth for all kinds of programmers"
3. "Empower, enthuse and facilitate education for programmers of all ages, experience levels and backgrounds"

@DDCreationStudios

**Comment by robeerob** [comment]
Let's discuss this together with overall prioritization/planning, in-person, in the near future? @DDCreationStudios

**Comment by DDCreationStudios** [comment]
@robeerob yes! let's do it 🚀

**Comment by DDCreationStudios** [comment]
## Long statement
> We help developers realize their goals, connect companies with potential hires, and fascilitate growth for all kinds of programmers.

## Short 
> Developers Rising - Help, connect and empower!
