### ISSUE TITLE
Make initial check with tax authorities

### ISSUE THREAD

**Issue by DDCreationStudios** [DevelopersRising/DevelopersRising#42]
Some things to consider
- Information regarding tax benefits are not legally binding (therefore not very reliable). Tax benefits can only be confirmed after an assessment
- At this date (22.10.2017)  I consider the Verein to be not taxable because
  - income form membership fees and sponsoring are not considered taxable for CIT ( it is not "income") see on [rz 157 of the official guidlines on non-profits](https://findok.bmf.gv.at/findok/resources/pdf/e4b97433-51f0-451e-907d-7c8df986db10/19960.6.-1.X.pdf)
  - in terms of VAT Sec2(5)Z5 UStG is applicable ( qualification as "Liebhaberei" - especially when financial activity is under 2.900EUR per year)
  - according to Sec120ff BAO all tax relevant activities have to be reported within 1 month
- things to check with the tax authorities can be
  - is the non-profit "steuerbegünstigt" (benefiting of tax excemptions)
  - is there anything else left to be reported

**Comment by DDCreationStudios** [comment]
@robeerob  please see my conclusions on taxability and in case of errors or misunderstanding let me know :)

**Comment by robeerob** [comment]
@DDCreationStudios Well done! Read and understood.

**Comment by DDCreationStudios** [comment]
email: post.fa06-ic12@bmf.gv.at
name: titze

**Comment by DDCreationStudios** [comment]
Sent mail to apply for a tax number on 31.10.2017. 
Reason for applying: 
- Applying for a tax number provides the proof that we as board members have acted diligently to act according to the law
- Applying for a number doesn't imply that we have to pay taxes, it rather gives as an opportunity to add more (even taxable) activities for our non-profit work
- Maybe this way we can get a statement regarding tax exemptions

@robeerob This issue is therefore to close :) In case of questions, reopen and ask :)
