### ISSUE TITLE
Working on group setup

### ISSUE THREAD

**Issue by DDCreationStudios** [DevelopersRising/DevelopersRising#45]
1. CSS Focus
1. React Focus
1. Free to choose (can be vue, angular)

**Comment by robeerob** [comment]
@DDCreationStudios We should also discuss time schedule and organization. I think you mentioned something like this: First netconomy talk and us introducing the event, then 1 hour group work, then 1 hour presentation.

I would suggest to set aside slightly more time for group work, and make the presentation part shorter. If they aren't able to present in their allotted timeslot, their work is anyways online for others to see later. We should also discuss if you and me simply present their work, we ask them, or they should chose a designated "leader/presenter" that does that. The only issue I see with the latter is that it would mean that the group, and especially one person, uses more time on preparing the presentation than the actual coding etc.

How about this time schedule?
- 30 minutes Netconomy talk
- 20 minutes us introduction talk
- 10 minute break
- 80 minutes group work
- 10 minute break
- 15 minute presentation time, with 5 minutes allotted to each team
- 15 minutes debrief and closing remarks from organizers

**Comment by DDCreationStudios** [comment]
@robeerob  Great idea!  

We need to consider, that Netconomy wants some time for a get-together. And I think the food will arrive at the end.  And I don't think that Neconomy needs 30min for their introduction. We don't really need a newsflash this time. We can add one and simply point to it. I think we can just introduce ourselves and explain the roadmap for the evening. Before dividing into groups we will have  a short intro of all people in order to group them. 
Maybe something like this:
1. max 30min Introduction (Netconomy + we)
1. 5min break
1. 80min code (dividing into groups and explain the rules + actual coding)
1. 5min break
1. 15min discussing 
1. 45min closing remarks and get-together

We don't have to be that strict. I would suggest to keep it flexible with the presentation and the get-together. 

What do you think?

**Comment by robeerob** [comment]
@DDCreationStudios Ok, that makes sense. Yes, your suggested schedule LGTM :+1:
