### ISSUE TITLE
Update CodeOfConduct.md link in Contributing.md

### ISSUE THREAD

**Issue by Otto-AA** [DevelopersRising/DevelopersRising#49]
Currently, in the Contributing.md is a broken link to the CodeOfConduct.md
It should be `./CODE_OF_CONDUCT.md` instead of `./CodeOfConduct.md`

If you want, I can open a pull request or you fix it yourself :)
-Otto

**Comment by DDCreationStudios** [comment]
HI Otto! Nice catch! Yes please open a PR. We can label it Hacktoberfest 🚀

**Comment by Scundered** [comment]
Opened a pull request :)
