### ISSUE TITLE
Public Relations / Marketing Management

### ISSUE THREAD

**Issue by DDCreationStudios** [DevelopersRising/DevelopersRising#51]
@robeerob Would you like to handle all our cooperations here on this repo as well? 
Like for example: https://reactday.berlin 

If yes I will create a project board so we can keep track of everything :)

**Comment by robeerob** [comment]
@DDCreationStudios Sure, but maybe just keep it in the sprint board, and we can take it on a case by case basis. That way the sprint more reflects the actual ongoing work that we do, and not just some random aspects. What do you think?

**Comment by DDCreationStudios** [comment]
@robeerob True! But what if a cooperation goes over for example 6months? Then we will have to track each ongoing cooperation on every sprint. And also might lose sight of all ongoing cooperations. 
With a separate issue on an own project, we can reference all cooperations in the sprint with a link to the project. We can classify all necessary actions with a single issue in the sprint. 
This way we reflect the work in the sprint, but also are flexible enough to handle more cooperations at once. 
What's your take on that?

**Comment by robeerob** [comment]
@DDCreationStudios Good point! Sure, let's do it like you described :)

**Comment by robeerob** [comment]
@DDCreationStudios Propose to close this task and move to DONE in sprint. Unless you intended for this task to include more tasks in this sprint?

**Comment by DDCreationStudios** [comment]
@robeerob I want to add the pr board :) I will move it to done when finished :)

**Comment by DDCreationStudios** [comment]
@robaxelsen See and extend if necessary : https://github.com/DevelopersRising/DevelopersRising/projects/7
