### ISSUE TITLE
Create a "How can I contribute" guide

### ISSUE THREAD

**Issue by DDCreationStudios** [DevelopersRising/DevelopersRising#52]
Create a file  (and also link it in our homepage) where we can redirect people, who want to help

**Comment by robeerob** [comment]
@DDCreationStudios Maybe assign this to me for next sprint?

**Comment by DDCreationStudios** [comment]
@robeerob Yes of course if you want to :) .But I think we should finish the [current sprint](https://github.com/DevelopersRising/DevelopersRising/projects/4) first before opening a new one. The tax stuff will need a little more time, so I would have planned another week (or a free week) for the current sprint.

**Comment by robeerob** [comment]
@DDCreationStudios Ok, sounds like a plan.

**Comment by robeerob** [comment]
@DDCreationStudios Did you have any specific thoughts on this? We already have a good CONTRIBUTING.md document in FCCVienna that we can copy paste and improve. Or did you mean more focused on getting people to take on one of our open positions?

**Comment by DDCreationStudios** [comment]
@robeerob 
The existing CONTRIBUTE.md is for describing how to actually contribute on our Github repo. 
For this issue we should create a document to direct people, who want to contribute to our organization/meetups in general, to. 

When someone writes " Hi , I like your page how can I contribute?", we should redirect this person to this document.
The document can include:
- actual physical work at our meetups
- contributing code
- sponsoring
- sending goodies
- promoting our pages 
- etc


The intention is to automate and generalize everything as far as possible, so we both can focus on  the most important stuff :)

**Comment by robeerob** [comment]
@DDCreationStudios Ok, I understand. And good point about automating and generalizing :)

My first thought is that is is a bit confusing, both for us and the members/contributors, to have a CONTRIBUTE.md file and a HOW-TO-CONTRIBUTE.md file, and a document listing positions that they can take on if they want to contribute. How about instead dropping the positions, and restructure it into "areas to help", and put in place a structure where people get stars/brownie points the more they help (maybe one issue per help action or something)?

**Comment by DDCreationStudios** [comment]
@robeerob  We definitely shouldn't name it HOW-TO-CONTRIBUTE.md 😆 
Very interesting idea and good point! But how to give out stars or brownies? :D 
Also good idea: So instead of standalone positions we can have contribution areas? 🚀 
Seems better because the threshold for doing something is lower 🌟

**Comment by robeerob** [comment]
@DDCreationStudios Hehe, yeah. Glad you liked the idea. Then, let's do this :tada: :smiley_cat: 

Not sure how to give the stars, but maybe just count number of issues closed to begin with?
