### ISSUE TITLE
Help & Engage

### ISSUE THREAD

**Issue by iepur1lla** [DevelopersRising/DevelopersRising#58]
Hey @robaxelsen, 
Hey @DDCreationStudios, 

all the best for the new year. I just wanted to thank you for the work you have done last year, and congratulate you on the success of Developers Rising Vienna. 

To keep the issue short and simple - I want to help you grow the community and engage with the developer scene in Vienna and beyond even more. For how we can do this, get in touch with [me](mailto:mario.kandut@gmail.com), so we can discuss the details.

**Comment by robaxelsen** [comment]
Hi @iepur1lla,

Happy New Year, friend :smile: Thanks a lot for the kind words, and great to hear that you want to get involved.

Will email you now so we can talk more :tada:
