### ISSUE TITLE
oktober and november meetup

### ISSUE THREAD

**Issue by DDCreationStudios** [DevelopersRising/DevelopersRising#6]

**Comment by robeerob** [comment]
Need to set date for October meetup.

**Comment by DDCreationStudios** [comment]
let's go with 20th of october? 🚀

**Comment by robeerob** [comment]
Yes, going with 20th of October, and I will contact Metalab about potentially having it there.

For October program we will be a talk by Juho Vepsäläinen and a bigger coding session.
