### ISSUE TITLE
Redirect developersrising domains to heroku site

### ISSUE THREAD

**Issue by robaxelsen** [DevelopersRising/DevelopersRising#64]

**Comment by robaxelsen** [comment]
Done:
[http://developersrising.com](http://developersrising.com)
[http://developersrising.com](http://developersrising.org)

**Comment by Createdd** [comment]
Awesome! 💪

**Comment by Createdd** [comment]
https not working? why is that?

**Comment by robaxelsen** [comment]
We need a cert for that on own servers I think. Right now I just redirected
the domain at registrar directly to heroku.

I propose that we create a separate issue for https, and investigate.
Probably exists tutorials for how to set up redirect with https for heroku.

**Comment by robaxelsen** [comment]
@Createdd see my last comment.

**Comment by Createdd** [comment]
True! Thanks @robaxelsen
