### ISSUE TITLE
Find new locations for 2018

### ISSUE THREAD

**Issue by Createdd** [DevelopersRising/DevelopersRising#66]
- [ ] 101 - inProgress
- [x] Certible - inProgress
- [ ] stockwerk?
- [ ] RIAT?
- [ ] WKO or other public sponsor?

**Comment by robaxelsen** [comment]
Good idea to make an issue. Added a couple more suggestions above.

**Comment by robaxelsen** [comment]
To summarize for posterity, we ended up with Certible, which turned out to be a great fit for us!
