### ISSUE TITLE
Need to inform that NGO no longer exists.

### ISSUE THREAD

**Issue by robaxelsen** [DevelopersRising/DevelopersRising#68]
Going to update README.md with a message to indicate this. Propose to leave repo as is for now for historical reasons, but open to other suggestions.

**Comment by Createdd** [comment]
Hi @robaxelsen !
yes, thanks for wrapping everything up :) 
agree a 100%. we can leave it as it is on github. and when github wants to take it down because the NGO is not alive anymore we can close it anyways :) 
otherwise we have the option to do something with it when an opportunity arises :)

**Comment by robaxelsen** [comment]
@Createdd awesome, and yw! let's close this then 😉👍
